//USER
export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_RED = "CREATE_USER_RED"
export const GET_USER = "GET_USER"
export const GET_USER_RED = "GET_USER_RED"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_RED = "UPDATE_USER_RED"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_RED = "DELETE_USER_RED"

//User Login and Logout
export const USER_LOGIN_RED = "USER_LOGIN_RED"
export const USER_LOGOUT_RED = "USER_LOGOUT_RED"


//CLASS
export const CREATE_CLASS = "CREATE_CLASS"
export const CREATE_CLASS_RED = "CREATE_CLASS_RED"
export const GET_CLASS = "GET_CLASS"
export const GET_CLASS_RED = "GET_CLASS_RED"
export const UPDATE_CLASS = "UPDATE_CLASS"
export const UPDATE_CLASS_RED = "UPDATE_CLASS_RED"
export const DELETE_CLASS = "DELETE_CLASS"
export const DELETE_CLASS_RED = "DELETE_CLASS_RED"


//EVENT
export const CREATE_EVENT = "CREATE_EVENT"
export const CREATE_EVENT_RED = "CREATE_EVENT_RED"
export const GET_EVENT = "GET_EVENT"
export const GET_EVENT_RED = "GET_EVENT_RED"
export const UPDATE_EVENT = "UPDATE_EVENT"
export const UPDATE_EVENT_RED = "UPDATE_EVENT_RED"
export const DELETE_EVENT = "DELETE_EVENT"
export const DELETE_EVENT_RED = "DELETE_EVENT_RED"
